### ISSUE TITLE
All Permits - Inspection Result Notifications

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#83] opened 2019-12-19 21:52 UTC
After speaking with Christian today (12/19) he said that the Inspection Result notification were disabled for all application types, due to issues it was causing for inspectors in the field.

I believe Christian is researching but, can we get clarification on whether or not these are still disabled and for which applications. At this point, the only applications that should not send inspection result notifications are Grading and FRO permits (see ticket #75 ).

**Comment by dhenry-KCI** [comment] 2019-12-23 04:25
@ScottVanSooy - please research this week as time allows.

**Comment by ScottVanSooy** [comment] 2019-12-23 19:32
Yes.   Christian gave them a work around, using a STOPNOT log to get past  the immediate error.  I can dig in, but it would be incredibly more efficient to use the work arounds and wait for Dan, if we can

**Comment by dhenry-KCI** [comment] 2019-12-23 19:36
I saw Christian’s workaround – if it would be better to wait that should be fine. I am following up with Juniata to ensure the workaround is effective.

**Comment by JuanitaMiles** [comment] 2019-12-23 20:38
This work around is something that will need to be added anytime this error occurs as the STOPNOT log needs to be individually added to each affected application. It has been applied by Christian to the two applications listed in this ticket so they can progress forward.

**Comment by calequin** [comment] 2020-01-09 21:17
promote BP_InspectionResultNotification_BU and enable

this is duplicate of #75

**Closed by calequin** 2020-01-09 21:17 UTC
Labels: Low Priority
