### ISSUE TITLE
GIS - Township Code on Address Issue - Need Infor Assistance

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#435] opened 2020-02-24 15:11 UTC
Creating a ticket for tracking...

Mary McCullough has discovered an issue where many of the Township codes on addresses in the system are not correct because there is no match of that address in GIS. Assistance from Infor has been requested to help query and bulk update these addresses. 

Details regarding this can be found in the 2/21 - 2/24 email chain. Dan has requested approval prior to working on this item.

**Comment by JuanitaMiles** [comment] 2020-02-24 15:42
Mary to provide a list of the addresses affected.

**Comment by JuanitaMiles** [comment] 2020-02-24 19:51
Mary has provided a spreadsheet that outlines the AddressKey and what the Township Code should be in the "ACTUAL_TOWNSHIP" field. See attached spreadsheet and Mary's email explanation below. 

There appears to be over 5500 addresses that need correcting. Pushing this ticket as a high priority. Will follow up with an email to the team.

[CorrectedTownships.xlsx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4246525/CorrectedTownships.xlsx)

![image](https://user-images.githubusercontent.com/31770504/75185864-d011a080-5714-11ea-8291-29e7756250d8.png)

**Comment by megisys** [comment] 2020-02-26 13:00
HI All,

We need to meet to discuss this, as things like this will come up all the time and we need to build this in a repeatable fashion. We do not support SQL updates to the database, so we should meet to talk about the best way to achieve this fix and other fixes which may come up.

Thanks

Dan

**Comment by ABonomo21** [comment] 2020-02-28 16:48
We need this fixed asap- here are example permits 266520,521,524&525 for properties located in brunswick crossing that have town water and sewer designations that triggered health review fees as if the water was on well and or septic. 

after staff emailed gis they explained they were waiting for infor support to get a fix for the area code issues. 

This can be very problematic if parcels do not have accurate information or are looking at multiple parcels, which ever the issue is as the parcel details drive reviews, fees and inspections for permits. how to we expedite this to who ever is responsible???  @JuanitaMiles 
![image](https://user-images.githubusercontent.com/47611580/75567804-20904300-5a20-11ea-9dba-26a02a954f35.png)

![image](https://user-images.githubusercontent.com/47611580/75567837-2d149b80-5a20-11ea-9bf1-85ffbc8e4dac.png)

**Comment by megisys** [comment] 2020-03-02 22:09
Updated in TEST due to urgency.. Please test in TEST and let me know

**Comment by megisys** [comment] 2020-03-02 22:10
UPDATE
    Property.Address
SET
    property.Address.TOWNSHIP = c.Townshipnew 
       
FROM 
    dbo.TownShip_CleanUp c
    INNER JOIN Property.Address t
        ON c.Addrkey = t.ADDRKEY

**Comment by ABonomo21** [comment] 2020-03-06 15:06
@JuanitaMiles dan assigned this one back to me? What am i supposed to test?

**Comment by JuanitaMiles** [comment] 2020-03-09 20:24
@megisys I've spot checked some of the addresses in Mary's spreadsheet (by looking up by linked parcel) and the Township on the address appears to be updated. I believe this update can be made in Prod.

@ABonomo21 This fix, however, is not related to the Health Review fee adding incorrectly. A different ticket will need to be created or reopened/updated. May need to clarify the logic on when Health Review Fee adds. Reopening ticket #12 . It appears the formula change Christian made as a result of that ticket does not fully meet the needed criteria.

**Comment by JuanitaMiles** [comment] 2020-03-09 20:26
Not reopening #12 as it does not discuss the Town piece specifically. Will create a new ticket and reference #12 .

**Comment by megisys** [comment] 2020-03-11 17:47
Completed in Prod

**Closed by megisys** 2020-03-11 17:47 UTC
Labels: Test Accepted
