### ISSUE TITLE
DPZ review in an incorporated town

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#443] opened 2020-02-25 16:47 UTC
a DPZ review populated on a permit that is located within the town limits of emmitsburg, DPZ review should not generate on properties within a municipality. 

![image](https://user-images.githubusercontent.com/47611580/75267736-9dbf7c00-57c4-11ea-80d1-6d7fb79c4a91.png)

**Comment by JuanitaMiles** [comment] 2020-02-25 18:51
Both the Address and Parcel records for this application indicate that the Township is 00 - County, which is likely the cause of the DPZ review still adding. If this is incorrect, please create a County GIS ticket for the gis team to investigate and update.

![image](https://user-images.githubusercontent.com/31770504/75277182-8c32a000-57d5-11ea-9b5f-4a8784f88a56.png)

![image](https://user-images.githubusercontent.com/31770504/75277295-b84e2100-57d5-11ea-8613-2fa2b266bdc3.png)

**Comment by JuanitaMiles** [comment] 2020-02-25 20:07
closing, ashlye is creating a GIS ticket.

**Closed by JuanitaMiles** 2020-02-25 20:07 UTC
Labels: Question / County Assistance
