### ISSUE TITLE
Planning - MY INFOR AUTO REFRESH - Not working

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#151] opened 2020-01-02 15:13 UTC
I had nothing in my to do list, I selected refresh aand a plan that cam in 13 minutes prior to the refresh showed up. I refreshed at 10:11 am and the project said it was added at 9:58 am
Please verify my auto refresh. AREED
![image](https://user-images.githubusercontent.com/58854333/71674155-8629c100-2d48-11ea-8a9f-ef29be0a0121.png)

**Comment by JuanitaMiles** [comment] 2020-01-02 19:05
I did a small test surrounding this potential issue. I looked at my dashboard initially to view the records/counts, then played around in the system for an extended period of time (more than 5 minutes) without returning to the My Infor window. Then after some time I returned to the My Infor window (it still had the same records and counts) and stayed there until it refreshed with the correct records/counts. 

From what I've seen, this appears to be a general product issue where the My Infor page does not auto refresh if you're not actually sitting on that page. I don't think it's an Ashley Reed specific issue.

**Comment by awhite806** [comment] 2020-01-03 14:39
This is happening with us in permits too. We are also noticing that when applicant resubmitals come in for their second completeness check, the application added date is still showing as the original submission date, not the applicant actions resubmittal time/date. these could be two separate issues, but Ashlye and I think they may be related.

**Comment by JuanitaMiles** [comment] 2020-01-03 14:56
@awhite806 The application date/time display is not an issue, and not related to the refresh. This is a standard field that has been added to the dashboards. It will always show the date the application was originally submitted.

**Comment by calequin** [comment] 2020-01-03 19:33
@JuanitaMiles this is on purpose by design. The auto refresh only works when on the myinfor screen, this was disabled because the auto refresh causes the screen to refresh while techs are in other screens. This would result in entering data and it getting cleared out every 5 minutes by nature of the product. The screen will refresh if you are in the myinfor page but needs to be refreshed by the user when viewing the landing page again.

**Comment by JuanitaMiles** [comment] 2020-01-03 20:58
Closing this ticket for now since there seems to be nothing we can do here. Staff will need to ensure they regularly refresh their dashboards.

**Closed by JuanitaMiles** 2020-01-03 20:58 UTC
Labels: High Priority, Ready for Retest
