### ISSUE TITLE
PLANNING/PERMITS - Temporary Passwords not being sent to new users for R4C login.

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#546] opened 2020-05-06 18:43 UTC
Project Number - PW260011/ grading permit  275459 
Observed behavior - New portal users are added and the portal account is created. A Temporary Password is assigned but never sent to the new user. When the new user goes to create an account, R4C tells them they already have an account. When they try to access the account the rescue password question is "when did you setup your account" which they don't know. The temporary password is in the log in IPS but is not sent to the user. 
Examples from frustrated engineer:
Project #:   PW260011
Client email: Jennifer.Busch@penntexventures.com
Project #:   275459
Client email: STEVE@HTANOW.COM

Expected behavior - The system needs to send a notification email to the new user, providing the temporary password. 
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/81215388-44837e00-8fa7-11ea-8ea3-86789e554897.png)

![image](https://user-images.githubusercontent.com/58854333/81215314-2ae23680-8fa7-11ea-9d2a-e677182d1062.png)

**Comment by pooldaddy** [comment] 2020-05-11 16:50
@JuanitaMiles  @Ycoto Have verified that an email was never created.  Configuration issue that needs to be looked at by Infor.
Assigning to megisys

**Comment by megisys** [comment] 2020-05-15 12:51
PLease Test -  and Promote  the following once apprvoed
SendNotify
BP_PortalAccountCreation_AAF
PL_AddRthyhmAccounts_AAF
PORTALC - Notification Template

**Comment by AReed327** [comment] 2020-05-15 19:47
PL260051 Retest failed. I created two new users and no emails were sent to provide them their temporary account information.
I only received the temporary passwords in the portal log 
![image](https://user-images.githubusercontent.com/58854333/82090126-fc5d0d80-96c2-11ea-850b-4813686c498c.png)

![image](https://user-images.githubusercontent.com/58854333/82090049-ce77c900-96c2-11ea-8f24-5a0e42a1f7d5.png)
![image](https://user-images.githubusercontent.com/58854333/82090296-51991f00-96c3-11ea-89c2-a9e2e4c8280f.png)

**Comment by megisys** [comment] 2020-05-18 12:36
In Test - All Emails will go to you the User. To Stop Test system emailing real people. So it wont show up on their Notifications. Should be yours. But let me retest. @AReed327

**Comment by megisys** [comment] 2020-05-18 13:03
Test was performed from Rhythm and as we are in test mode. Is emailing the email address associated with Hansen8. Please test from back office.

**Comment by AReed327** [comment] 2020-05-18 13:35
Email received. SP260052
![image](https://user-images.githubusercontent.com/58854333/82219061-c7330400-98ea-11ea-82b0-2a6f8c79c1f5.png)
![image](https://user-images.githubusercontent.com/58854333/82219140-dc0f9780-98ea-11ea-911e-9c1e1d834448.png)

**Comment by AReed327** [comment] 2020-06-01 15:22
This is not working in Production.
- The temporary password is not provided in the email.
- The link to the portal in the email is not working. It does not take you to the public portal.
[Frederick County - Portal Account Registered Email to new user.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4712055/Frederick.County.-.Portal.Account.Registered.Email.to.new.user.pdf)
[RE_ F260106 New User Email.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4712056/RE_.F260106.New.User.Email.pdf)
![image](https://user-images.githubusercontent.com/58854333/83424139-03418b00-a3fa-11ea-8a2b-f5942564b473.png)
![image](https://user-images.githubusercontent.com/58854333/83424284-3552ed00-a3fa-11ea-9dda-01d7d4f5fef5.png)

**Comment by megisys** [comment] 2020-06-01 15:32
Hi Ashley, 

How did this contact get created. The Email Address was not valid. I fixed it now

**Comment by megisys** [comment] 2020-06-01 15:32
Please try again

**Comment by AReed327** [comment] 2020-06-01 15:55
How was the email not valid? I added them through the contact details tab and saved the row. This is not something I can just test. I need to wait until I have another new portal user. Also, I''m confused because they received the email. That does not indicate an invalid email.

**Comment by megisys** [comment] 2020-06-01 15:58
The Notification says it didn't send in your image

**Comment by AReed327** [comment] 2020-06-02 13:32
I know it says that but I attached the email that they received. I also provided a screenshot above.

**Comment by AReed327** [comment] 2020-06-02 15:40
This is not resolved. I have another new applicant. 
richard@casasmd.com
![image](https://user-images.githubusercontent.com/58854333/83539858-91cf0e80-a4c5-11ea-8203-0654e61e5cb4.png)
There is nothing wrong with this email
![image](https://user-images.githubusercontent.com/58854333/83539966-b4f9be00-a4c5-11ea-97c6-d57547fafa12.png)

![image](https://user-images.githubusercontent.com/58854333/83540025-c5119d80-a4c5-11ea-8188-168a51cb674b.png)

**Comment by AReed327** [comment] 2020-06-02 16:06
Once again an email went out even though the system message says notification was unable to send. The portal link in the email that was sent does not take you to the portal. The temporary password is not provided in the email. Today when I clicked the portal link in the email, it gave me a message that says Can't reach this page.
![image](https://user-images.githubusercontent.com/58854333/83541573-cf349b80-a4c7-11ea-8477-7e9ae79345c7.png)
![image](https://user-images.githubusercontent.com/58854333/83541626-e07da800-a4c7-11ea-9571-77d29a6c58f9.png)

**Comment by megisys** [comment] 2020-06-03 12:42
POrtal Link is addressed in Production.. working on Issue of Failed Delivery and the content

**Comment by AReed327** [comment] 2020-06-03 14:24
Results from Webex with Dan 6/3/2002

Govolution is not making the connection due to no address on contacts created from the contact details tab. Contact details only requests first/last name, phone and email.

Dan to update all new contacts which have rhythm accounts to be Unknown 00000 and ask them to update on first log in.

**Comment by megisys** [comment] 2020-06-03 14:31
ContactUtils - Formula to be promoted.
Notification is updated

**Comment by JuanitaMiles** [comment] 2020-06-03 15:01
Ash B. received the same type of error from one of her customers. Can we confirm the highlighted email/user meets the same criteria as the above identified issue. See email below, and ensure the fix will be applied to all applicable modules.

![image](https://user-images.githubusercontent.com/31770504/83653224-7dece080-a589-11ea-835e-de715c08051b.png)

**Comment by JuanitaMiles** [comment] 2020-06-05 17:28
@megisys Can you work with @pooldaddy and @Ycoto to sort out any additional work that needs to be done regarding the account creation notifications containing temp passwords and the solution of the address for portal payments. I'd like Jeff and Yaciel to have a full understanding of the issue, how it can be resolved and assist with any testing that needs to be done. Then we can have Ashley confirm once you feel you've reached an acceptable resolution.

**Comment by AReed327** [comment] 2020-06-09 12:47
This new portal contact does not have an address of unknown. I thought that was going to be corrected when Dan said all customers were able to pay online.

![image](https://user-images.githubusercontent.com/58854333/84148545-29d07900-aa2d-11ea-9313-7f54a40aad04.png)

It is still saying notification didn't send with it sends.
![image](https://user-images.githubusercontent.com/58854333/84148922-abc0a200-aa2d-11ea-83f8-a70e2bd0ae71.png)

**Comment by megisys** [comment] 2020-06-15 15:10
Hi There, I tested this in Test. for PWConstruct and all seems to be working

![image](https://user-images.githubusercontent.com/47392306/84674291-c34dce00-aef8-11ea-91c4-1b36f5aae982.png)

**Comment by JuanitaMiles** [comment] 2020-06-19 13:44
Confirmed with Dan that the notification is working in production as designed. will create a new ticket to reevaluate the process as a whole in next phase. and will have a meeting to discuss

**Comment by JuanitaMiles** [comment] 2020-06-19 16:29
Ticket has been created in Future Phase repository for re-evaluation in the next phase of the project. We will meet to discuss an acceptable workaround for editing the contact details page after is has already been submitted.
[Ticket 96](https://github.com/JuanitaMiles/FredCo_Future_Phases/issues/96)

Closing this ticket as Dan has confirmed the configuration for the email is working properly in production when contact detail is entered and checkbox is checked upon initial creation.

**Closed by JuanitaMiles** 2020-06-19 16:29 UTC
