### ISSUE TITLE
11 month extension letter

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#106] opened 2019-12-20 19:58 UTC
language needs to be updated we no longer use the attachments referenced in the highlighted. I thought these changes were made on this report? 

![image](https://user-images.githubusercontent.com/47611580/71288257-95684200-2338-11ea-93cf-d370ff00b0c8.png)

A should read "Please log into your citizen portal account and complete the _extension request detail_ page for this permit to submit your request...."

B should read "Please log into your citizen portal account and to submit your request to void..."

**Comment by TaraF** [comment] 2019-12-23 20:31
Per conversation with @ABonomo21 on 12/23/19, updating section A text to read:

"Please log into your citizen portal account and complete the extension request detail page for this permit to submit your request for the extension of the referenced residential bldg uses permit.  Upon extension granted, a fee of $49.00 is required. "

**Comment by ABonomo21** [comment] 2019-12-27 15:40
good

**Comment by TaraF** [comment] 2019-12-30 02:43
This is complete, ready for re-test.

**Comment by emilypearl1** [comment] 2020-02-12 19:05
Re- opening Ticket- would like to make changes to the wording of the 11 Month Grading and Expired  Grading Permit notices

11 Month Notice:
![image](https://user-images.githubusercontent.com/58855801/74367683-47a01100-4da0-11ea-8c10-85b3c2cbc59d.png)

Expired Notice (2nd Notice):
![image](https://user-images.githubusercontent.com/58855801/74367752-64d4df80-4da0-11ea-8498-c0235aca6412.png)

Change to: "Please log into your citizen portal account and complete the extension request detail page for this permit to submit your request for the extension of the referenced Grading permit. Upon extension granted, the applicable fees will be applied. "

**Comment by TaraF** [comment] 2020-02-13 19:33
Assigned, in progress.

**Comment by TaraF** [comment] 2020-02-18 18:29
@emilypearl1  - the above text update has been made to both reports.  Please test in Test to confirm.

@JuanitaMiles  - once confirmed, this is just a report move from SSRS Test to Production - and can be assigned to Jeff W. or myself.

**Comment by emilypearl1** [comment] 2020-02-19 15:55
Grading Permits- Expiration Notice - looks good in test- READY TO DEPLOY.
Grading Permits- Expiration Notice (2nd Letter)- have a few minor edits to the wording. 

Please change to:  
"In order to retroactively extend the permit, please log into your citizen portal account and complete the extension request detail page for this permit to submit for the extension of the referenced Grading permit. Upon extension granted, the applicable fees will be applied. "

Once the wording is updated on the Grading Permits- Expiration Notice (2nd Letter)- it is ready for production.

**Comment by TaraF** [comment] 2020-02-20 15:19
Latest request assigned, in progress.

**Comment by TaraF** [comment] 2020-02-21 17:51
@emilypearl1  - this is ready for testing in Test.

@JuanitaMiles  - once Emily is able to approve please reassign to me to promote to prod (since Jeff W is on vacation - I believe).

**Comment by ABonomo21** [comment] 2020-02-21 18:07
Looks good in test- Juanita- please promote to production.

**Comment by ABonomo21** [comment] 2020-02-21 18:08
checked by EPEARL 2/21/2020 @ 1:08pm

**Comment by TaraF** [comment] 2020-02-25 17:11
promoted to Prod 2/25/20.

**Closed by TaraF** 2020-02-25 17:11 UTC
Labels: Needs Promotion to Prod, Test Accepted
