### ISSUE TITLE
Error in Mobile

### ISSUE THREAD

**Issue by TheBobEnsor** [dhenry-KCI/FredCo-Post-Go-Live-#454] opened 2020-03-02 11:31 UTC

**Comment by TheBobEnsor** [comment] 2020-03-02 11:35
We have been seeing this error on occasion and just want to document it 
See picture of error attached
![Exception in Map Provider](https://user-images.githubusercontent.com/60886453/75673030-02108e80-5c50-11ea-9d77-eef52ef48031.jpg)

**Comment by TheBobEnsor** [comment] 2020-03-02 13:22
A little more info, it appears when opening "Building Permits"/ Nearby open

**Comment by JuanitaMiles** [comment] 2020-03-02 13:36
@pooldaddy Jeff as you investigate this issue, it might be related to ticket #452 - Map Functionality not working.

**Comment by pooldaddy** [comment] 2020-03-04 18:31
@JuanitaMiles @TheBobEnsor #452 has been resolved in PRoduction.  That should also fix this issue.  Please verify in PROD and if ok close this ticket.

**Comment by JuanitaMiles** [comment] 2020-03-23 16:39
@TheBobEnsor Bob can you confirm whether or not this error is still appearing for you or your guys? I believe it was linked to an overall map issue that has since been fixed. If this is no longer an issue. Please close the ticket.

**Comment by ABonomo21** [comment] 2020-04-03 12:55
confirmed with Bob the error is no longer occurring. 
Thanks

**Closed by ABonomo21** 2020-04-03 12:55 UTC
Labels: Ready for Testing in TEST
