### ISSUE TITLE
RESSFD Fees incorrect

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#441] opened 2020-02-25 15:55 UTC
For this SFD permit, only the building fee and the SCD review fee generated. It is missing everything else (zoning, filing, automation, minor grading, stormwater, mpdu fees). Not sure what cause this??
![image](https://user-images.githubusercontent.com/58981029/75264382-58e41700-57bd-11ea-86c0-96c0c3fd307f.png)

**Comment by megisys** [comment] 2020-02-26 19:16
HI There, (Jeff and Dan together)

eems we had a GIS update reinstate the PlanR of FR. This logic was retired and rather than adjust all the pre written formulas it was decided to ensure in the future to not set this attribute.

I update the PLNR on the AgencyProperty.ParcelDet to be Null where FR to avoid wrong fees on new building permits

![image](https://user-images.githubusercontent.com/47392306/75378896-85be2a00-58a2-11ea-899b-aed8a503cfc9.png)

**Comment by JuanitaMiles** [comment] 2020-02-26 20:24
Jeff has emailed Mary and Austin regarding this on 2/26.

**Comment by ABonomo21** [comment] 2020-02-27 14:29
Dan confirmed the error occurred because the FR was added back into the planning region on the parcels- This was working prior to Mary making this change. 

Dwelling fees were working correctly prior to the change - test accepted as long as it is put back the way it was before the GIS change.

**Comment by JuanitaMiles** [comment] 2020-02-28 21:22
It appears all steps have been taken to correct the errant population of the Plan Region. Closing ticket, if the issue re-appears again in the future we will need to reopen and re-evaluate the the issue.

**Closed by JuanitaMiles** 2020-02-28 21:22 UTC
Labels: Deployed to Production
