### ISSUE TITLE
Opening attachments on Mac (Infor Xtreme #14213852)

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#230] opened 2020-01-14 16:23 UTC
MGraham@ramcopermits.com 
customer cannot open attachments on mac
258907
258908
258912,13,14,15,16

**Comment by megisys** [comment] 2020-01-14 18:06
Hi Ashlye, what would you like Infor to do here. we dont support citizen's macbooks

**Comment by ABonomo21** [comment] 2020-01-15 19:51
I believe this was discussed in a separate meeting. But i think we can all agree the Infor product need to work on all products.

**Comment by calequin** [comment] 2020-01-16 00:29
Hi Ashlye this has been moved over to our development team for further research. I want to clarify that the issue is not the mac computer but whenever a user utilizes an iphone or ipad to download an attachment. The attachment tries to save as a .pdf.png and doesnt display. I also notice that the download button is not available on the device unless you tilt the device.

**Comment by calequin** [comment] 2020-01-21 17:02
call scheduled with a Frederick County applicant to view their mac set up and gather information. Call on 1.21.2020 at 3pm EST

**Comment by megisys** [comment] 2020-01-23 19:11
Issue is identified as a product issue . Currently we have work around for come customers. Update required from Product. here.

**Comment by megisys** [comment] 2020-01-23 20:39
Meeting set for Tomorrow

**Comment by megisys** [comment] 2020-01-27 13:23
IOS Features are coming in future release. So IoS is truly a new requirement but is coming.
Issues with MAC on certain operating systems, our recommendation at this point is to use Chrome browser.

**Comment by megisys** [comment] 2020-01-29 14:55
Please add disclaimer to R4C about combination of Apple OS and Browser

**Comment by calequin** [comment] 2020-01-29 22:55
![40A44A70-3184-4F8C-9531-0A30F27A7A7D](https://user-images.githubusercontent.com/47603568/73404844-157ab380-42b8-11ea-8cd3-293bdb585d80.png)

**Comment by JuanitaMiles** [comment] 2020-02-04 18:43
@ABonomo21 Can we close this issue and track as an enhancement since it appears Infor product team intends to make improvement in future releases? Christian has put the disclaimer in place.

**Comment by JuanitaMiles** [comment] 2020-02-06 22:05
clsoing, tracking as enhance in future phase list

**Closed by JuanitaMiles** 2020-02-06 22:05 UTC
Labels: Enhancement, Infor Support Ticket, Medium Priority, Question / County Assistance
