### ISSUE TITLE
Sign Permit-Bldg fee/review still generating

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#307] opened 2020-01-28 17:27 UTC
Per Ashlye, the building fee and review should not generate on building mounted signs. permit #262084 is a building mounted channel letter sign and the fee/review still generated
![image](https://user-images.githubusercontent.com/58981029/73288693-737c9d80-41c9-11ea-8bd6-d6733c6cd8d5.png)
![image](https://user-images.githubusercontent.com/58981029/73288709-7aa3ab80-41c9-11ea-8494-59c68f342a7a.png)

**Comment by megisys** [comment] 2020-01-28 18:04
![image](https://user-images.githubusercontent.com/47392306/73291672-a5443300-41ce-11ea-9d40-6a554ac35c4b.png)

Which ones do we add on please ?

**Comment by calequin** [comment] 2020-01-28 18:12
fixed in test. once approved promote
SIGN_PLNREV_Review_AOC
SIGN_Building_Fee_AOC

**Comment by calequin** [comment] 2020-01-28 19:02
@awhite806 which types are building mounted?

**Comment by ABonomo21** [comment] 2020-01-28 19:37
Freestanding and Monument Signs only should have a building fee
![image](https://user-images.githubusercontent.com/47611580/73298622-a62f9180-41db-11ea-9ae7-b8a988f9edd8.png)

**Comment by calequin** [comment] 2020-01-28 20:19
fixed in test. once approved promote
SIGN_PLNREV_Review_AOC
SIGN_Building_Fee_AOC

**Comment by ABonomo21** [comment] 2020-01-28 20:28
tested application 259440 and it still generated the building fee- see sign detail page is not marked for any freestanding...

**Comment by ABonomo21** [comment] 2020-01-28 20:31
just the fee generated not the review... neither the fee or the review should generate

**Comment by ABonomo21** [comment] 2020-01-28 20:33
![image](https://user-images.githubusercontent.com/47611580/73302992-974cdd00-41e3-11ea-873c-b5bade64c639.png)
confirmed worked in test

**Comment by ABonomo21** [comment] 2020-02-17 13:40
processed a freestanding sign # 264830 and the building fee did not generate.

**Comment by ABonomo21** [comment] 2020-02-17 13:40
had to manually add

**Comment by calequin** [comment] 2020-02-19 14:54
looks like this ticket was never promoted to Prod. Can we retes in TEST and verify if promotion is needed.

**Comment by calequin** [comment] 2020-02-19 15:07
Tested on 263357 once accepted please promote
SIGN_Building_Fee_AOC

**Comment by calequin** [comment] 2020-02-23 15:07
promoted on 2.23.2020

**Comment by ABonomo21** [comment] 2020-02-25 18:50
reopening- building mounted sign generated the building review 
![image](https://user-images.githubusercontent.com/47611580/75277318-c3a14c80-57d5-11ea-817c-787edeb568b2.png)

**Comment by JuanitaMiles** [comment] 2020-02-26 20:18
PLNREV potentially added due to the "OTHER" sign type on the detail page, which cancelled out the coding behind the building mounted sign not requiring a PLNREV. We need to understand how to handle these "other" instances so the code can be updated or put a SOP process in place to waive the plan review when it's not required.

**Comment by megisys** [comment] 2020-02-27 14:18
Update Made.. Only Freestanding, Monument will be reviewed.. Other Type may be an issue as it is unclear what this is..

**Comment by ABonomo21** [comment] 2020-02-27 14:25
tested 263398 for freestanding 263399 monument and 263397 all others- all worked correctly on building freestanding and monument signs triggered the building plan review fee and the review.

**Closed** 2020-03-01 16:33 UTC
Labels: Deployed to Production
