### ISSUE TITLE
New DUSWM Planning AP Type

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#531] opened 2020-04-20 18:00 UTC
Source:
Meetings
Requested By: Mike WIlkins, Ashley Reed

Request:
DUSWM staff that reviews planning applications sometimes have a need to create new back office planning application for things like City projects because DUSWM still manages their utilities. DUSWM is currently creating applications with the AP types that currently exist, however this is causing confusion and extra staff efforts due to a need to consistently waive fees, reviews, hearings, etc.

To eliminate this issue, it would be ideal to have a separate AP type where DUSWM can create the necessary application for their office only. The initial thought is that this application type can have Work Type options that would include Site,Plat, PWConstruct, etc. The workflow/milestones will be minimal.

**Comment by JuanitaMiles** [comment] 2020-04-20 18:00
Currently working with Mike and Ashley to document workflow and details. Will attach documentation here once finalized.

**Comment by JuanitaMiles** [comment] 2020-04-21 17:01
Detailed requirements for this AP Type are outlined in the documents below. These details have been reviewed and confirmed with Ashley R and Mike Wilkins. This documentation should be referenced while creating all steps in the DUSWMPL Application Type:

1) DUSWM_Requirements_v2.1 - Outlines all requirements for each milestone. This includes review types, result codes, condition types, fees, reports, etc.

2) DUSWM_Workflow_v2.1 - SOP style workflow documentation to outline the process for end users.

3) DUSWMPL_Detail_Page_v2.1 - Mock up of the new detail page that should be created for the AP Type.

[DUSWMPL_Detail_Page_v2.1.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4511372/DUSWMPL_Detail_Page_v2.1.pdf)
[DUSWM_Requirements_v2.1.xlsx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4511373/DUSWM_Requirements_v2.1.xlsx)
[DUSWM_Workflow_v2.1.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4511374/DUSWM_Workflow_v2.1.pdf)

**Comment by megisys** [comment] 2020-05-05 14:42
70% Complete in Production - AS Copy to Test going to happen this week and didn't want to loss work. Need to complete rest out of hours @JuanitaMiles

**Comment by JuanitaMiles** [comment] 2020-05-05 17:59
@megisys Application expiry should be 5 years and begin once the fees have been paid.

**Comment by JuanitaMiles** [comment] 2020-05-05 18:17
Permissions for the DUSWM ap have been set in Prod for the Super User access group only for now. Once everything has been tested, accepted, and finalized, I will implement the appropriate permissions for the DUSWM role.

**Comment by megisys** [comment] 2020-05-19 13:13
This is ready for Testing in Test

**Comment by AReed327** [comment] 2020-05-20 18:48
Intake Review SOP
2) Input the Subdivision Code on the Job Description tab.
I thought it would have the same redline condition that required the subdivision code to be selected before moving out of the Intake Review Milestone. Can we add that so it doesn't get missed?
------------------------------------------------------------------------

The Contact Details is available when setting up the application as requested. What implications does this cause. Can you see an issue with people trying to pay fees online or add attachments online. Is it really an issue if they do? This feature links it to their portal accounts. 
![image](https://user-images.githubusercontent.com/58854333/82482098-53d4f200-9aa4-11ea-9c96-bbd78837bad2.png)

![image](https://user-images.githubusercontent.com/58854333/82482271-9991ba80-9aa4-11ea-9462-2d9a0b68f366.png)
------------


DUSWM Review set to 8 days right now. Can it be reset to 3 weeks? That is the standard review time.
![image](https://user-images.githubusercontent.com/58854333/82482713-3eac9300-9aa5-11ea-93f2-fdd03bab63a9.png)
--------------------------------------

Problems field to be set up to log comments that need to be addressed by the engineer/applicant

![image](https://user-images.githubusercontent.com/58854333/82482951-9a771c00-9aa5-11ea-9eb8-884fffbdf886.png)

@JuanitaMiles We will also need to have the reports pointed at this Application Type so DUSWM can provide the comment report to the applicant.
 No changes to the report data, just needs to pull from DUSWM application
![image](https://user-images.githubusercontent.com/58854333/82483458-6d773900-9aa6-11ea-9bac-0ef612c27136.png)

-------------

Application did not progress after review was resulted as resubmit to make the awaiting applicant resubmit/under review loop until review is approved.
![image](https://user-images.githubusercontent.com/58854333/82484003-4a995480-9aa7-11ea-9bb0-917a9e46b0e7.png)

**Comment by megisys** [comment] 2020-05-21 14:09
Hi There, This application was no slated for online @JuanitaMiles  from my understanding ?

**Comment by megisys** [comment] 2020-05-21 14:14
These areas have been addressed

**Comment by AReed327** [comment] 2020-05-21 14:20
@megisys The goal was to not have it online. My concern is that when they link applicants with active portal accounts, what is keeping it from linking to their portal? I'm trying to determine or discuss, if there is nothing to keep it from linking to the portal account, does that cause issues? I would anticipate, if it did show up on an applicants portal, the applicant would likely try to pay the fees online. I am fine if we can keep it from linking. Not sure how that would work.

**Comment by JuanitaMiles** [comment] 2020-05-21 14:35
I think if we keep the "Show in Portal" checkbox unchecked on the AP type, this would prevent it from being visible at all right? Even if it does get created with an applicant with a portal account. Either way the application wouldn't allow submission on the portal but the show in portal being deselected will also make it unsearchable as well. @megisys Is this correct?

**Comment by megisys** [comment] 2020-05-21 14:35
This application type will not show up online. As it is show in portal = False. Also there are no notifications for this AP Type. I can ensure portal accounts are not created for any DUSWM applications

**Comment by JuanitaMiles** [comment] 2020-05-21 19:00
I've tested 3 Work Types (APFO, Plat, PWConstruc). My detailed list of items below:

### **1) Application Creation/Submittal:**

- **Work Type = APFO** - PASSED (no issues)

- **Work Type = PLAT** : Update spelling on Plat Details page from "Total Areas" to "Total Acres".
![image](https://user-images.githubusercontent.com/31770504/82593353-61f04480-9b70-11ea-9d90-935e8a539dbf.png)

- **Work Type = PWCONSTRUC** : Update spelling on PWConstruc Details page from "Acerage" to "Acreage".
![image](https://user-images.githubusercontent.com/31770504/82593488-96fc9700-9b70-11ea-9f19-bcb2fc7d0791.png)

### **2) Intake Review:**

- **Work Type = APFO/PLAT/PWCONSTRUC:** PASSED (no issues)
@AReed327 Initially we had the ADDFEES condition needing to be required at Intake rather than having a separate "add fees" milestone. Can you confirm if you are okay with leaving the add fees in its own milestone or if you would like Dan to configure it the way we originally proposed?

### **3) Awaiting Applicant Resubmit:**

- **Work Type = APFO/PLAT/PWCONSTRUC:** PASSED (no issues)

### **4) Add Plan Review Fees:**

- **Work Type = APFO/PLAT/PWCONSTRUC:** Would like to confirm with @AReed327 that it is okay to have this separate milestone rather than combining with Intake Review. Otherwise, PASSED (no issues).

### **5) Awaiting Plan Review Payment:**

- **Work Type = APFO/PLAT/PWCONSTRUC:** PASSED (no issues)

### **6) Under Review:**

- **Work Type = APFO/PLAT/PWCONSTRUC**:
      DUSWME review result options currently show the standard completeness check review option. The DUSWME options should only be Approved and Resubmit.

### **7) Awaiting Applicant Revisions**

- **Work Type = APFO/PLAT/PWCONSTRUC**: PASSED (no issues)

### **8) Admin Closure:**

- **Work Type = APFO/PLAT**: These work types should not progress to Admin Closure. Only PWConstrucs should move to Admin Closure

- **Work Type = PWCONSTRUC**: Status at Admin Closure shows as Closed. Status should remain Open until application is complete.

**Comment by AReed327** [comment] 2020-05-21 20:26
"I can ensure portal accounts are not created for any DUSWM applications" - PERFECT!

**Comment by AReed327** [comment] 2020-05-22 12:35
D260059 I added a name in contact details under the DUSWM worktype and it sent me the new portal user temporary password email. I don't want that to happen and confuse people on DUSWM only projects.
![image](https://user-images.githubusercontent.com/58854333/82668028-ef7e7380-9c06-11ea-8a41-77c26952813a.png)
![image](https://user-images.githubusercontent.com/58854333/82668137-20f73f00-9c07-11ea-86cb-abf5a3562fa1.png)

**Comment by AReed327** [comment] 2020-05-22 12:59
1) Application Creation/Submittal: D260059
•	Work Type = SITE Passed
2) Intake Review:
•	Work Type = SITE Passed
3) Awaiting Applicant Resubmit:
•	Work Type = SITE Passed
4) Add Plan Review Fees:
•	Work Type = SITE/ALL - Fine with me to have this separate milestone rather than combining with Intake Review. PASSED (no issues)
5) Awaiting Plan Review Payment:
•	Work Type = SITE Passed
6) Under Review:
•	Work Type = SITE - Adding PROBLEMS – worked
**•	Wrong list of review results. This is the list for completeness check. Should be approved or resubmit only.**
![image](https://user-images.githubusercontent.com/58854333/82669614-beec0900-9c09-11ea-9b37-2cd8341f340f.png)
	 
7) Awaiting Applicant Revisions
•	Work Type = SITE - Passed
8) Admin Closure:
•	Work Type = SITE** Couldn't test as no approved option on the review.**

**Comment by megisys** [comment] 2020-05-22 13:07
@AReed327 - I have fixed the portal creation issue for DUSWM planning AP's this will not happen

**Comment by megisys** [comment] 2020-05-22 13:09
@AReed327 - Review Codes Fixed

**Comment by AReed327** [comment] 2020-05-26 17:03
D260059 SITE worktype- should have closed/complete upon approval of review
Application stopped at admin closure milestone and asked for PWCONSTRUC worktype mylar check condition.
![image](https://user-images.githubusercontent.com/58854333/82929155-37780000-9f51-11ea-89f8-9be45bf9b7f3.png)

**Comment by AReed327** [comment] 2020-05-26 17:18
@JuanitaMiles We need to add assigning all reviews in the SOP/status check window so they do not stay on my Planning dashboards if they follow the directions correctly. I would think we should include it at completeness check and when the review populates "under review". Do you have any other ideas as to how we can keep these tasks off of my dashboards? I don't think making the dashboard search more complicated is ideal based on all of the trouble we have had with review assignments.  AR

**Comment by AReed327** [comment] 2020-05-26 17:40
Application Creation/Submittal: D260060
• Work Type = PREPLAT

Intake Review:
• Work Type = PREPLAT Passed (there are additional options here that are not necessary but it works. The good thing is ePlans is not an option)

Awaiting Applicant Resubmit:
• Work Type = PREPLAT - Passed. Tested on D260061 since I passed this on the first one.

Add Plan Review Fees:
• Work Type = PREPLAT - Passed

Awaiting Plan Review Payment:
• Work Type = PREPLAT - Passed

Under Review:
• Work Type = PREPLAT - Please add note "Do Not Use" under the Transfer description. If this is selected it will not transfer to the next review cycle. This should be on all work types. 
![image](https://user-images.githubusercontent.com/58854333/82931701-52e50a00-9f55-11ea-8e61-592fec7b2f42.png)


Awaiting Applicant Revisions
• Work Type = PREPLAT - Passed

Admin Closure:
• Work Type = PREPLAT - Remove DUSWM MYLAR condition and appication should go to "finalized" milestone. Mylar condition is only for PWCONSTRUC work type.
![image](https://user-images.githubusercontent.com/58854333/82931896-9b042c80-9f55-11ea-8e02-27501e0902ea.png)

**Comment by megisys** [comment] 2020-05-27 09:48
@AReed327 @JuanitaMiles  - This has been adjusted

**Comment by AReed327** [comment] 2020-05-27 14:48
D260062 - Verified reports work for Application Details and Project Pending Letter. Verified problems populated and dropped off with addressed resolution code and they transferred to following cycle if not resulted.
D260062 - PREPLAT - PASSED - Closed and Finalized

D260063 - APFO
After review approval should go to closed/finalized. 
Remove DUSUM Mylar condition as it should only be on PWCONSTRUC work type
![image](https://user-images.githubusercontent.com/58854333/83032346-b594df00-a003-11ea-9106-375aeefe2af6.png)
![image](https://user-images.githubusercontent.com/58854333/83032406-c80f1880-a003-11ea-8a74-df98304d401a.png)



D260064 - PWCONSTRUC - 

Application should not be closed until after the mylar condition is marked Yes.
![image](https://user-images.githubusercontent.com/58854333/83033941-b62e7500-a005-11ea-9fd2-14f58c39c0c7.png)
![image](https://user-images.githubusercontent.com/58854333/83033985-bfb7dd00-a005-11ea-9264-993d0e12dbc0.png)


D260065 - PLAT
Remove DUSWM mylar check from PLAT work type. Review approval should go to closed/finalized
![image](https://user-images.githubusercontent.com/58854333/83034606-6e5c1d80-a006-11ea-9fe0-709e25103414.png)
![image](https://user-images.githubusercontent.com/58854333/83034672-803dc080-a006-11ea-9e2d-4e85db945779.png)



D260066 - SITE
Remove DUSWM mylar check from PLAT work type. Review approval should go to closed/finalized
![image](https://user-images.githubusercontent.com/58854333/83035457-7bc5d780-a007-11ea-9e8e-d1bf6575e1f8.png)
![image](https://user-images.githubusercontent.com/58854333/83035555-9b5d0000-a007-11ea-8e0a-569e530031c8.png)

**Comment by megisys** [comment] 2020-05-28 11:54
This is fixed @AReed327

**Comment by AReed327** [comment] 2020-05-28 12:45
D260067 - APFO - verified corrected closed/finalized
D260068 - PLAT - verified corrected closed/finalized
D260069 - PREPLAT - verified corrected closed/finalized
D260070 - SITE - verified corrected closed/finalized
D260071 - PWCONSTRUC - Confirmed application still went to admin closure with condition for mylars - once condition resulted yes - application progressed to closed/finalized

**Comment by megisys** [comment] 2020-05-31 12:57
Deployed

**Closed by megisys** 2020-05-31 12:57 UTC
Labels: Deployed to Production, Enhancement/Upcoming Release, May 23rd Release, Test Accepted
