### ISSUE TITLE
Placards generating on Trade permits after Extension Approval

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#320] opened 2020-01-30 20:10 UTC
After Emily approved this permit extension review for an Electrical permit., four Building permit placards generated as an attachment and they are all blank.
building permits placards should not generate on electrical permits.
![image](https://user-images.githubusercontent.com/58981029/73486184-99917180-4372-11ea-989b-35865e6dea18.png)
![image](https://user-images.githubusercontent.com/58981029/73486199-a31ad980-4372-11ea-81d2-60aab30e4c76.png)

**Comment by TaraF** [comment] 2020-01-31 20:51
Holding on this assignment until Infor upgrade is complete next week.

**Comment by TaraF** [comment] 2020-02-06 17:31
@megisys  - can you take a look at this please? I am wondering if this has to do with the CM you did specifically for the Extension approval process.

 For the regular correspondence  - we only have the official issuance set to those ELECPERM, no placard.
![image](https://user-images.githubusercontent.com/4104464/73961557-d6adb480-48da-11ea-92d6-69e5cb33239d.png)
 
The only place we have correspondence on building placards is on RESBLDG, DEMOLITION, TRAILER, SIGNS, TANKS, NONRESBLDG, RESUSES.
[image](https://user-images.githubusercontent.com/4104464/73962068-b8948400-48db-11ea-85ae-6f33e050054c.png)

**Comment by megisys** [comment] 2020-02-06 18:32
Fee_ProcessExtension_BU - Update . Promote if Testing is successful

**Comment by ABonomo21** [comment] 2020-02-06 20:51
tested the extension process on 263249, everything worked but did not get the new official issuance - ran batch manager and it did not work...

**Comment by megisys** [comment] 2020-02-07 13:45
THis is due to Tara and the COunty needing to promote Production reports to TEST. Assigning to County and TAra

**Comment by TaraF** [comment] 2020-02-10 16:26
Test environment is up and running for reports.

**Comment by JuanitaMiles** [comment] 2020-02-10 21:22
Please retest in test now that the reports test environment is setup.

**Comment by ABonomo21** [comment] 2020-02-12 19:08
tested 263280 - added placard- retest failed 
![image](https://user-images.githubusercontent.com/47611580/74368178-1d028800-4da1-11ea-81ef-e880cb8e35e6.png)
![image](https://user-images.githubusercontent.com/47611580/74368216-2e4b9480-4da1-11ea-983f-faf0a9736bc3.png)

**Comment by JuanitaMiles** [comment] 2020-02-13 14:23
@calequin Please look into the formula Dan implemented in the thread above to try to understand why this item is not working properly. Tara has already confirmed that the test environment for reports has been setup.

**Comment by calequin** [comment] 2020-02-21 15:49
Please test once accepted promote formula:
Fee_ProcessExtension_BU

**Comment by ABonomo21** [comment] 2020-02-21 20:25
placard did not generate 
![image](https://user-images.githubusercontent.com/47611580/75069032-57b1a200-54be-11ea-9c7a-558d45f60cc0.png)

**Comment by calequin** [comment] 2020-02-23 15:08
promoted on 2.23.2020

**Closed** 2020-02-23 15:37 UTC
Labels: Deployed to Production
