### ISSUE TITLE
town review 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#110] opened 2019-12-23 15:45 UTC
town review will not allow completeness check to be resulted get the error that no contact information is available for this town review..
![image](https://user-images.githubusercontent.com/47611580/71366855-380b0580-2571-11ea-8090-e34af1dae6e1.png)
removed applicant to progress past completeness check 
this is a reoccuring issue

**Comment by ABonomo21** [comment] 2019-12-27 15:12
this is still having a problem- see permit 258732

**Comment by ScottVanSooy** [comment] 2020-01-09 18:19
Issue cannot be replicated see permit in test

**Comment by awhite806** [comment] 2020-01-27 14:17
Re-opening. this issue is still occurring. #261979 would not let me result the completeness check due to the town reviewer being on as an applicant. I was able to get the completeness check resulted when adding the STOPNOT log. 

![image](https://user-images.githubusercontent.com/58981029/73180938-486c4e00-40e4-11ea-883a-f16ce1734b07.png)
![image](https://user-images.githubusercontent.com/58981029/73180985-5f12a500-40e4-11ea-9477-78f6df0cda4d.png)

**Comment by calequin** [comment] 2020-01-27 15:23
the township code on this address in 01 therefore adding BRUNSWICK as the reviewer. The reviewer notification formula was fixed in test and needs to be deployed. Please test in test.

**Comment by awhite806** [comment] 2020-01-27 17:57
Since the "Deployed to Production" was on this ticket, I was under the impression that it had already been sent to IPS Prod. I've tested it in IPS test and it seems to be working.

![image](https://user-images.githubusercontent.com/58981029/73200297-7e212f00-4104-11ea-80aa-b1be39726ac5.png)

**Comment by ABonomo21** [comment] 2020-01-27 18:35
per meeting 1.27.20 dan will be working on this issue

**Comment by megisys** [comment] 2020-01-27 18:35
•	When an application has been processed - Meaning, when the Completeness Check review has been resulted and the Processed Date has been applied to the application. I don’t believe this is currently a notification we have but it will be extremely useful to the Towns.

•	When the Permit has been Issued - We have this notification already for Building and Use.

•	Final Inspection Result Notification – While the Town should not receive every inspection result notification, those that are a “final” should be sent.

•	COO/COC correspondence – The Town should be receiving the final correspondence that contains the COO or COC attachment. The typical process for these was that the Town would be the only one to receive these documents then they would provide them to the applicant.

Thanks,

**Comment by megisys** [comment] 2020-02-03 22:48
Started work on this in TEST. AS this is half complete. TOwnR will get no Use or Building Notifications in TEST

**Comment by awhite806** [comment] 2020-02-05 17:22
Permit #263364  and #263363 were both processed at the same time, one by Shannon and the other by Linda. Shannon's permit #263364 processed through completeness check with no issue. Linda's permit #263363, would not let her proceed past the completeness check unless she entered the STOPNOT log to bypass the town reviewer email. Both permits are for the town of Brunswick.

**Comment by ABonomo21** [comment] 2020-02-06 17:56
Got another Town Reviewer Error on Permit 264523
![image](https://user-images.githubusercontent.com/47611580/73964389-13c87580-48e0-11ea-8ca7-c18f3a128c7d.png)

**Comment by megisys** [comment] 2020-02-08 13:56
•	When an application has been processed - Meaning, when the Completeness Check review has been resulted and the Processed Date has been applied to the application. I don’t believe this is currently a notification we have but it will be extremely useful to the Towns. - DONE !!

### **Promote - BP_NotifyTownReviewers**

•	When the Permit has been Issued - We have this notification already for Building and Use. - ### **BP_IssuePermitNotification Updated**

•	Final Inspection Result Notification – While the Town should not receive every inspection result notification, those that are a “final” should be sent.

**### BP_FinalNotTown_AOC**

Add Condition to All Town Reviewed Applications and add above formula

•	COO/COC correspondence – The Town should be receiving the final correspondence that contains the COO or COC attachment. The typical process for these was that the Town would be the only one to receive these documents then they would provide them to the applicant.

### **- BP_COR_COO to be promoted** 

Thanks,

**Comment by megisys** [comment] 2020-02-08 14:00
PLease TEST RESBLDG, RESUSES and NONRESBLDG.. Let me know which other application a town might want to be informed of final inspections being completed please..

Add yourself as a TOWNR to see this..

**Comment by megisys** [comment] 2020-02-08 14:03
Template TownUpdate need to be promoted and added to config editor

**Comment by megisys** [comment] 2020-02-08 14:04
Opt Out also Fixed for Contractors

**Comment by ABonomo21** [comment] 2020-02-12 17:38
tested on 263345 worked - duplicated from a current production permit 264800 which did not work to confirm that this was an accurate test!

**Comment by calequin** [comment] 2020-02-16 16:03
promoted on 2.16.2020

**Comment by JuanitaMiles** [comment] 2020-04-16 15:04
work via webex with Dan on town notifications still not sending out.

**Comment by JuanitaMiles** [comment] 2020-04-27 16:42
Reopening Ticket - 

Town notifications still do not appear to be working as expected in Production. A couple of examples below:

1) RESUSES Permit 275500 was created on 4/23 and Issued on 4/24. Town Reviewer, Middletown, did not receive the notification indicating the application has been accepted by the county (completeness check approval), and it did not receive the town version of the Issued notification that I received when testing in test. They got the universal issued notification only because they are not opted out of that template.

2) Grading permit 271590 was issued on 4/23 and the town of Brunswick did not get a notification of issuance.

![image](https://user-images.githubusercontent.com/31770504/80395031-ad207b80-8880-11ea-8d11-260a317f3865.png)
![image](https://user-images.githubusercontent.com/31770504/80395193-da6d2980-8880-11ea-8005-c548eb4ba822.png)

**Comment by JuanitaMiles** [comment] 2020-04-27 16:53
Add RESUSE AP # 275527 to the list of not getting the initial application accepted email after approving completeness check.

**Comment by JuanitaMiles** [comment] 2020-04-28 19:55
Spoke w/ AB on 4/28. Upgrading to high priority.

**Comment by megisys** [comment] 2020-04-28 22:14
Fixed in Production - Due to Urgency tonight. Tested in Test only. Confident issue is fixed.

**Comment by JuanitaMiles** [comment] 2020-04-29 14:35
I will review again in a few days to confirm any town notifications that might be applicable.

**Comment by JuanitaMiles** [comment] 2020-05-04 18:17
ResUse AP # 276859 - Application was processed 5/4 8:44 am and is now Under Review. The Middletown Town Reviewer contact did not receive the initial "application accepted in a town" email after approving the completeness check. In addition, the issued emails that went out to the are not the Town version, they are the standard ones that are getting sent because they are not opted out of it.

![image](https://user-images.githubusercontent.com/31770504/80998465-03596580-8e11-11ea-97bc-8110fdc42abb.png)
![image](https://user-images.githubusercontent.com/31770504/80998487-0bb1a080-8e11-11ea-8f8d-faa11a67dacb.png)
![image](https://user-images.githubusercontent.com/31770504/80998703-621edf00-8e11-11ea-8c7c-e0d5c1bad93a.png)

**Comment by JuanitaMiles** [comment] 2020-05-04 18:21
Walkersville AP # 276797 - Application Processed 5/1 did not get application accepted notification.  AP # 275527 was issued on 5/1, did not get the Town issued notification.

Myersville AP # 200594 - Application issued on 5/1, did not get the Town issued notification.

**Comment by megisys** [comment] 2020-05-04 20:48
![image](https://user-images.githubusercontent.com/47392306/81012140-0e1ef500-8e27-11ea-94b8-b82995e94aa7.png)

**Comment by JuanitaMiles** [comment] 2020-05-07 17:20
Confirmed on several towns that they have been getting the "TownUpdate" notifications since end of 5/4. There are still issues with the language on the notification, but I will open a separate ticket.

![image](https://user-images.githubusercontent.com/31770504/81324833-870b9000-9065-11ea-87f2-373a9b803ef6.png)

**Closed by JuanitaMiles** 2020-05-07 17:20 UTC
Labels: Deployed to Production
