### ISSUE TITLE
Service Request Attachments

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#361] opened 2020-02-06 15:48 UTC
Unable to open attachments on service request 1725

**Comment by megisys** [comment] 2020-02-06 15:58
This ticket isnt enough to be a ticket

**Comment by JuanitaMiles** [comment] 2020-02-06 16:00
@ABonomo21 please provide screenshots with which attachments you are trying to open and the environment you are in.

**Comment by megisys** [comment] 2020-02-06 16:28
same as issue #337

**Comment by megisys** [comment] 2020-02-06 18:35
Work around in place to open these. can this be closed.. Emails as an allowable type needs to be approved by both Gary and Rick Little from a IT security stand point

**Comment by JuanitaMiles** [comment] 2020-02-07 18:38
Closing as a duplicate of the solution for ticket 337. Gary's final confirmation comments below.

![image](https://user-images.githubusercontent.com/31770504/74055950-f9a99880-49ae-11ea-98de-72feb3f65e74.png)

**Closed by JuanitaMiles** 2020-02-07 18:38 UTC
Labels: Question / County Assistance
