### ISSUE TITLE
PLANNING - R4C - MAP FUNCTION NOT WORKING

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#452] opened 2020-02-28 16:34 UTC
Project Number - New Project in R4C
Observed behavior - Scroll in on map under search for address and you cannot make a selection. This is not working in Test or Production R4C
Expected behavior - Expect to be able to select property by the map function. 
Screenshot -
Production
![image](https://user-images.githubusercontent.com/58854333/75566671-18370880-5a1e-11ea-91b8-73d48a2da37b.png)
Test
![image](https://user-images.githubusercontent.com/58854333/75566702-2a18ab80-5a1e-11ea-87e7-c1fac93c6506.png)

**Comment by pooldaddy** [comment] 2020-03-02 14:55
@megisys Able to replicate the issue in Production.  Forwarding to you for next steps.  Also please take a look at 454 as it may be related.

**Comment by pooldaddy** [comment] 2020-03-02 18:18
Extreme Ticket Created

![image](https://user-images.githubusercontent.com/47391482/75704940-4f105700-5c88-11ea-8ff2-b7d4b57b3382.png)

**Comment by pooldaddy** [comment] 2020-03-03 13:24
@AReed327 Ashley, we made a change on the GIS side, please confirm this is now working. Thanks.

**Comment by MLWilkins** [comment] 2020-03-03 17:08
@pooldaddy  AReed tested in Production and it is working.  Unable to test in test as test enviro is down.

**Comment by JuanitaMiles** [comment] 2020-03-03 19:38
@pooldaddy Can you confirm that the change made for GIS will be effective for both Prod and Test environments? And if this fix also addresses ticket #454 ? If so, please mark that ticket ready for testing as well. 

@MLWilkins Once we get confirmation the fix is effective for both environments, we can close this ticket.

**Comment by pooldaddy** [comment] 2020-03-04 18:26
@JuanitaMiles fix should resolve both TEST & Prod environments.

**Comment by pooldaddy** [comment] 2020-03-04 18:29
Ready for R4C Test verification once #468 resolved

**Comment by JuanitaMiles** [comment] 2020-03-11 17:51
#468 Has now been resolved and is awaiting final confirmation from county staff. 

@MLWilkins and @AReed327 please confirm the map functionality works in Test R4C as well. If confirmed in Test, I think we can close this ticket since it was previously confirmed to be working again in Prod.

**Comment by MLWilkins** [comment] 2020-03-12 12:47
fixed- A258911

**Closed by MLWilkins** 2020-03-12 12:47 UTC
Labels: Ready for Testing in TEST
